// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CallMCPTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearChat():Promise<void>;

export function ClearProviderKey(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function ExportChat():Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAvailableModels():Promise<Array<main.ModelOption>>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetChatHistory():Promise<Array<main.ChatMessage>>;

export function GetCurrentShell():Promise<string>;

export function GetCwd():Promise<string>;

export function GetFileIcon(arg1:string):Promise<string>;

export function GetGitBranches():Promise<Array<string>>;

export function GetGitGraph(arg1:number):Promise<Array<main.GitLogEntry>>;

export function GetGitInfo():Promise<main.GitInfo>;

export function GetKnowledgePacks():Promise<Array<main.KnowledgePack>>;

export function GetMCPServers():Promise<Array<main.mcpServerStatus>>;

export function GetMetrics():Promise<main.Metrics>;

export function GetModel():Promise<string>;

export function GetProblems(arg1:string):Promise<Array<main.Problem>>;

export function GetProviders():Promise<Array<main.ProviderListEntry>>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetRunTargets():Promise<Array<main.RunTarget>>;

export function GetSearchLimit():Promise<number>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSkills():Promise<Array<main.SkillEntry>>;

export function GitCheckout(arg1:string):Promise<string>;

export function GitCommit(arg1:string):Promise<string>;

export function GitCreateBranch(arg1:string):Promise<string>;

export function GitDiff():Promise<string>;

export function GitDiffFile(arg1:string):Promise<string>;

export function GitLog(arg1:number):Promise<string>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function GitStage(arg1:string):Promise<void>;

export function GitUnstage(arg1:string):Promise<void>;

export function ListFiles(arg1:string,arg2:number):Promise<Array<main.FileEntry>>;

export function ListSessions():Promise<Array<main.ChatSession>>;

export function LoadSession(arg1:string):Promise<void>;

export function OpenFolder():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadSkill(arg1:string):Promise<string>;

export function RefreshMCPServers():Promise<Array<main.mcpServerStatus>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function RunTarget(arg1:string):Promise<void>;

export function SaveDroppedFile(arg1:string,arg2:Array<number>):Promise<string>;

export function SaveProviderConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSession(arg1:string):Promise<string>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchInFiles(arg1:string,arg2:string):Promise<Array<main.SearchResult>>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCwd(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetShell(arg1:string):Promise<void>;

export function SnapshotCount():Promise<number>;

export function StartLiveServer(arg1:string):Promise<string>;

export function StartTerminal():Promise<void>;

export function StopMCP():Promise<void>;

export function StopTerminal():Promise<void>;

export function SwitchModel(arg1:string):Promise<string>;

export function ToggleKnowledgePack(arg1:string,arg2:boolean):Promise<void>;

export function UndoLastEdit():Promise<string>;

export function WalkProject():Promise<Array<main.FileEntry>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
