// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallMCPTool'](arg1, arg2, arg3);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function ClearProviderKey(arg1) {
  return window['go']['main']['App']['ClearProviderKey'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ExportChat() {
  return window['go']['main']['App']['ExportChat']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetCurrentShell() {
  return window['go']['main']['App']['GetCurrentShell']();
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GetFileIcon(arg1) {
  return window['go']['main']['App']['GetFileIcon'](arg1);
}

export function GetGitBranches() {
  return window['go']['main']['App']['GetGitBranches']();
}

export function GetGitGraph(arg1) {
  return window['go']['main']['App']['GetGitGraph'](arg1);
}

export function GetGitInfo() {
  return window['go']['main']['App']['GetGitInfo']();
}

export function GetKnowledgePacks() {
  return window['go']['main']['App']['GetKnowledgePacks']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetModel() {
  return window['go']['main']['App']['GetModel']();
}

export function GetProblems(arg1) {
  return window['go']['main']['App']['GetProblems'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetRunTargets() {
  return window['go']['main']['App']['GetRunTargets']();
}

export function GetSearchLimit() {
  return window['go']['main']['App']['GetSearchLimit']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GitCheckout(arg1) {
  return window['go']['main']['App']['GitCheckout'](arg1);
}

export function GitCommit(arg1) {
  return window['go']['main']['App']['GitCommit'](arg1);
}

export function GitCreateBranch(arg1) {
  return window['go']['main']['App']['GitCreateBranch'](arg1);
}

export function GitDiff() {
  return window['go']['main']['App']['GitDiff']();
}

export function GitDiffFile(arg1) {
  return window['go']['main']['App']['GitDiffFile'](arg1);
}

export function GitLog(arg1) {
  return window['go']['main']['App']['GitLog'](arg1);
}

export function GitPull() {
  return window['go']['main']['App']['GitPull']();
}

export function GitPush() {
  return window['go']['main']['App']['GitPush']();
}

export function GitStage(arg1) {
  return window['go']['main']['App']['GitStage'](arg1);
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadSkill(arg1) {
  return window['go']['main']['App']['ReadSkill'](arg1);
}

export function RefreshMCPServers() {
  return window['go']['main']['App']['RefreshMCPServers']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function RunTarget(arg1) {
  return window['go']['main']['App']['RunTarget'](arg1);
}

export function SaveDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDroppedFile'](arg1, arg2);
}

export function SaveProviderConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProviderConfig'](arg1, arg2, arg3);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SearchInFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCwd(arg1) {
  return window['go']['main']['App']['SetCwd'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetShell(arg1) {
  return window['go']['main']['App']['SetShell'](arg1);
}

export function SnapshotCount() {
  return window['go']['main']['App']['SnapshotCount']();
}

export function StartLiveServer(arg1) {
  return window['go']['main']['App']['StartLiveServer'](arg1);
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function StopMCP() {
  return window['go']['main']['App']['StopMCP']();
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function ToggleKnowledgePack(arg1, arg2) {
  return window['go']['main']['App']['ToggleKnowledgePack'](arg1, arg2);
}

export function UndoLastEdit() {
  return window['go']['main']['App']['UndoLastEdit']();
}

export function WalkProject() {
  return window['go']['main']['App']['WalkProject']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
