package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/flykimjiwon/hanimo/internal/config"
)

const maxInitDepth = 4
const maxInitFiles = 500

// GenerateProjectProfile scans the current directory and produces
// a comprehensive markdown profile suitable for .hanimo.md.
func GenerateProjectProfile(dir string) string {
	if dir == "" {
		dir = "."
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Sprintf("Error: %v", err)
	}

	// Auto-create .hanimo/ subdirectories
	for _, sub := range []string{"knowledge", "commands"} {
		_ = os.MkdirAll(filepath.Join(absDir, ".hanimo", sub), 0755)
	}
	config.DebugLog("[INIT] ensured .hanimo/knowledge/ and .hanimo/commands/ exist")

	var sb strings.Builder
	projName := filepath.Base(absDir)

	sb.WriteString(fmt.Sprintf("# %s\n\n", projName))

	// Project detection
	info := DetectProject(dir)
	if info.Type != "unknown" {
		sb.WriteString("## Project Info\n\n")
		sb.WriteString(fmt.Sprintf("- **Type**: %s\n", info.Type))
		if info.Name != "" {
			sb.WriteString(fmt.Sprintf("- **Name**: %s\n", info.Name))
		}
		if info.Framework != "" {
			sb.WriteString(fmt.Sprintf("- **Framework**: %s\n", info.Framework))
		}
		if len(info.KeyFiles) > 0 {
			sb.WriteString(fmt.Sprintf("- **Key files**: %s\n", strings.Join(info.KeyFiles, ", ")))
		}
		sb.WriteString("\n")
	}

	// Directory tree
	sb.WriteString("## Directory Structure\n\n```\n")
	tree := initBuildTree(absDir, "", 0)
	sb.WriteString(tree)
	sb.WriteString("```\n\n")

	// Dependencies
	deps := initReadDependencies(absDir, info.Type)
	if deps != "" {
		sb.WriteString("## Dependencies\n\n")
		sb.WriteString(deps)
		sb.WriteString("\n")
	}

	// Entry points
	entries := initFindEntryPoints(absDir, info.Type)
	if len(entries) > 0 {
		sb.WriteString("## Entry Points\n\n")
		for _, e := range entries {
			sb.WriteString(fmt.Sprintf("- `%s`\n", e))
		}
		sb.WriteString("\n")
	}

	// Scripts (package.json scripts, Makefile targets)
	scripts := initReadScripts(absDir, info.Type)
	if scripts != "" {
		sb.WriteString("## Scripts / Commands\n\n")
		sb.WriteString(scripts)
		sb.WriteString("\n")
	}

	// Git info
	gitInfo := initReadGitInfo(absDir)
	if gitInfo != "" {
		sb.WriteString("## Git\n\n")
		sb.WriteString(gitInfo)
		sb.WriteString("\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("*Generated by `/init`. Edit freely — this file is loaded into AI context on every session.*\n")

	config.DebugLog("[INIT] generated profile for %s (%d bytes)", absDir, sb.Len())
	return sb.String()
}

func initBuildTree(root, prefix string, depth int) string {
	if depth > maxInitDepth {
		return ""
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		return ""
	}

	// Sort: dirs first, then files
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].IsDir() != entries[j].IsDir() {
			return entries[i].IsDir()
		}
		return entries[i].Name() < entries[j].Name()
	})

	// Filter out noise
	var filtered []os.DirEntry
	for _, e := range entries {
		name := e.Name()
		if defaultSkipDirs[name] || name == ".DS_Store" || strings.HasPrefix(name, ".") {
			continue
		}
		filtered = append(filtered, e)
	}

	var sb strings.Builder
	for i, e := range filtered {
		isLast := i == len(filtered)-1
		connector := "├── "
		childPrefix := "│   "
		if isLast {
			connector = "└── "
			childPrefix = "    "
		}

		if e.IsDir() {
			sb.WriteString(fmt.Sprintf("%s%s%s/\n", prefix, connector, e.Name()))
			sub := initBuildTree(filepath.Join(root, e.Name()), prefix+childPrefix, depth+1)
			sb.WriteString(sub)
		} else {
			sb.WriteString(fmt.Sprintf("%s%s%s\n", prefix, connector, e.Name()))
		}
	}
	return sb.String()
}

func initReadDependencies(dir, projType string) string {
	switch projType {
	case "go":
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err != nil {
			return ""
		}
		var deps []string
		inRequire := false
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "require (" {
				inRequire = true
				continue
			}
			if line == ")" {
				inRequire = false
				continue
			}
			if inRequire && !strings.Contains(line, "// indirect") {
				parts := strings.Fields(line)
				if len(parts) >= 2 {
					deps = append(deps, fmt.Sprintf("- `%s` %s", parts[0], parts[1]))
				}
			}
		}
		if len(deps) > 0 {
			return strings.Join(deps, "\n") + "\n"
		}

	case "node":
		data, err := os.ReadFile(filepath.Join(dir, "package.json"))
		if err != nil {
			return ""
		}
		content := string(data)
		var deps []string
		// Simple extraction of dependencies keys
		for _, section := range []string{`"dependencies"`, `"devDependencies"`} {
			idx := strings.Index(content, section)
			if idx < 0 {
				continue
			}
			start := strings.IndexByte(content[idx:], '{')
			if start < 0 {
				continue
			}
			end := strings.IndexByte(content[idx+start:], '}')
			if end < 0 {
				continue
			}
			block := content[idx+start+1 : idx+start+end]
			for _, line := range strings.Split(block, "\n") {
				line = strings.TrimSpace(line)
				line = strings.TrimSuffix(line, ",")
				if strings.Contains(line, ":") {
					deps = append(deps, fmt.Sprintf("- %s", line))
				}
			}
		}
		if len(deps) > 0 {
			return strings.Join(deps, "\n") + "\n"
		}

	case "python":
		data, err := os.ReadFile(filepath.Join(dir, "requirements.txt"))
		if err != nil {
			return ""
		}
		var deps []string
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line != "" && !strings.HasPrefix(line, "#") {
				deps = append(deps, fmt.Sprintf("- `%s`", line))
			}
		}
		if len(deps) > 0 {
			return strings.Join(deps, "\n") + "\n"
		}
	}
	return ""
}

func initFindEntryPoints(dir, projType string) []string {
	var entries []string
	candidates := map[string][]string{
		"go":     {"cmd/*/main.go", "main.go"},
		"node":   {"src/index.ts", "src/index.js", "src/main.ts", "src/main.js", "index.ts", "index.js", "src/app.ts", "src/app.js"},
		"python": {"main.py", "app.py", "src/main.py", "manage.py"},
		"rust":   {"src/main.rs"},
		"java":   {"src/main/java/**/Application.java", "src/main/java/**/Main.java"},
	}

	patterns, ok := candidates[projType]
	if !ok {
		return nil
	}

	for _, pattern := range patterns {
		matches, _ := filepath.Glob(filepath.Join(dir, pattern))
		for _, m := range matches {
			rel, _ := filepath.Rel(dir, m)
			entries = append(entries, rel)
		}
	}
	return entries
}

func initReadScripts(dir, projType string) string {
	var results []string

	// package.json scripts
	if data, err := os.ReadFile(filepath.Join(dir, "package.json")); err == nil {
		content := string(data)
		if idx := strings.Index(content, `"scripts"`); idx >= 0 {
			start := strings.IndexByte(content[idx:], '{')
			if start >= 0 {
				end := strings.IndexByte(content[idx+start:], '}')
				if end >= 0 {
					block := content[idx+start+1 : idx+start+end]
					for _, line := range strings.Split(block, "\n") {
						line = strings.TrimSpace(line)
						line = strings.TrimSuffix(line, ",")
						if strings.Contains(line, ":") {
							results = append(results, fmt.Sprintf("- %s", line))
						}
					}
				}
			}
		}
	}

	// Makefile targets
	if data, err := os.ReadFile(filepath.Join(dir, "Makefile")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.Contains(line, ":") && !strings.HasPrefix(line, "\t") && !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, ".") {
				parts := strings.SplitN(line, ":", 2)
				target := strings.TrimSpace(parts[0])
				if target != "" && !strings.Contains(target, "=") && !strings.Contains(target, " ") {
					results = append(results, fmt.Sprintf("- `make %s`", target))
				}
			}
		}
	}

	if len(results) > 0 {
		return strings.Join(results, "\n") + "\n"
	}
	return ""
}

func initReadGitInfo(dir string) string {
	// Check if .git exists
	if _, err := os.Stat(filepath.Join(dir, ".git")); err != nil {
		return ""
	}

	var lines []string
	lines = append(lines, "- Git repository detected")

	// Read .gitignore summary
	if data, err := os.ReadFile(filepath.Join(dir, ".gitignore")); err == nil {
		gitignoreLines := strings.Split(string(data), "\n")
		count := 0
		for _, l := range gitignoreLines {
			l = strings.TrimSpace(l)
			if l != "" && !strings.HasPrefix(l, "#") {
				count++
			}
		}
		lines = append(lines, fmt.Sprintf("- `.gitignore`: %d patterns", count))
	}

	return strings.Join(lines, "\n") + "\n"
}

// CollectKeyFiles reads the most important project files for LLM deep analysis.
// Returns concatenated file contents with headers, limited to maxFiles.
func CollectKeyFiles(dir string, maxFiles int) string {
	if dir == "" {
		dir = "."
	}
	absDir, _ := filepath.Abs(dir)

	// Priority order: most informative files first
	candidates := []string{
		"README.md", "README", "readme.md",
		"package.json", "go.mod", "Cargo.toml", "pyproject.toml", "pom.xml",
		"Makefile", "Dockerfile", "docker-compose.yml", "docker-compose.yaml",
		".env.example", ".env.sample",
		"tsconfig.json", "next.config.js", "next.config.ts", "next.config.mjs",
		"vite.config.ts", "webpack.config.js",
		".github/workflows/ci.yml", ".github/workflows/ci.yaml",
		".github/workflows/build.yml", ".github/workflows/deploy.yml",
		"Jenkinsfile",
		".hanimo.md", "AGENTS.md", "CLAUDE.md",
	}

	// Also find main entry points
	entryGlobs := []string{
		"cmd/*/main.go", "main.go",
		"src/index.ts", "src/index.js", "src/main.ts", "src/app.ts",
		"app.py", "main.py", "manage.py",
		"src/main.rs",
	}

	var sb strings.Builder
	collected := 0

	for _, candidate := range candidates {
		if collected >= maxFiles {
			break
		}
		path := filepath.Join(absDir, candidate)
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		content := string(data)
		// Limit per-file content
		runes := []rune(content)
		if len(runes) > 3000 {
			content = string(runes[:3000]) + "\n... [truncated]"
		}
		sb.WriteString(fmt.Sprintf("\n### %s\n```\n%s\n```\n", candidate, content))
		collected++
	}

	// Entry points
	for _, pattern := range entryGlobs {
		if collected >= maxFiles {
			break
		}
		matches, _ := filepath.Glob(filepath.Join(absDir, pattern))
		for _, match := range matches {
			if collected >= maxFiles {
				break
			}
			rel, _ := filepath.Rel(absDir, match)
			data, err := os.ReadFile(match)
			if err != nil {
				continue
			}
			content := string(data)
			runes := []rune(content)
			if len(runes) > 3000 {
				content = string(runes[:3000]) + "\n... [truncated]"
			}
			sb.WriteString(fmt.Sprintf("\n### %s\n```\n%s\n```\n", rel, content))
			collected++
		}
	}

	config.DebugLog("[INIT-DEEP] collected %d key files for LLM analysis", collected)
	return sb.String()
}
